# Generated by Django 3.1.1 on 2020-09-03 23:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=datetime.datetime(2020, 9, 3, 23, 36, 23, 47960, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
